### ISSUE TITLE
Key not found: Steam

### ISSUE THREAD

**Issue by juxuanu** [nning/protonutils#15]
```
╰─❱ protonutils list 
Key not found: Steam
```
```
╰─❱ protonutils config                                                   
user: ""
```

I just installed [protonutils](https://aur.archlinux.org/packages/protonutils) and it can't list games nor config. I don't know how can I make it work. I have Steam installed and a couple of games as well, one of them require Proton (I have [proton-ge-custom](https://aur.archlinux.org/packages/proton-ge-custom/) installed), which is used for that game (which is Poppy Playtime). I also have a non-Steam game added to my library and a couple of native games.

**Comment by nning** [comment]
Thanks for trying `protonutils` and for reporting this issue!

`protonutils config` should actually show an empty config unless any values are set explicitly by the user.

All the features should work without explicitly specifying the Steam user in the config.

However, `protonutils list` should work right away just as you tried and yield no such error!

Please answer some questions to pinpoint this issue:
1. Did you enable Steam Play for all titles?
1. Did you override the default Proton version for "Poppy Playtime"?
1. Which version of `protonutils` are you using?

It looks like the "CompatToolMapping" configuration is looking different than on my machines (or is empty).

Would you send me your `~/.steam/root/config/config.vdf` via mail, please?

**Comment by juxuanu** [comment]
1. I did not, but I just tried enabling Proton-GE globally and I still got the same error.
2. Yes, with proton-ge-custom
3. 1.3.1-1

I'll send you an email with the requested file right away.

**Comment by nning** [comment]
Thanks for sending the file! In your config, the "CompatToolMapping" is saved under a lower case "steam" key, whereas in my config (and seemingly also for the majority of other users), the mapping is saved under a capitalized "Steam" key.

I changed the code to try both, now.

Please retest with and report back:
https://github.com/nning/protonutils/suites/4648747079/artifacts/126140837

**Comment by juxuanu** [comment]
That works 👍🏻

**Comment by nning** [comment]
Great, thanks for your help!
