### ISSUE TITLE
feature request: remove unused prefixes

### ISSUE THREAD

**Issue by matthewlenz** [nning/protonutils#22]
Option to remove prefixes (yes, I'm aware I could lose my saved games) by game or all unused.

**Comment by nning** [comment]
I agree, thanks for the suggestion! I already thought in that direction a bit and I'm planning different `compatdata` commands like clean-up, backup, and so on.

**Comment by nning** [comment]
Implemented in `v1.6.1`:
https://github.com/nning/protonutils/releases/tag/v1.6.1
