### ISSUE TITLE
"list" command gives me a "vdf: unknown pack type 101" error

### ISSUE THREAD

**Issue by crlmahlberg** [nning/protonutils#25]
Hello. I have not been using `protonutils` for a while and just downloaded the latest version. Upon running `list`, the program gives me the following error: `vdf: unknown pack type 101`. Any thoughts? I manually edited _~/.steam/steam/config/config.vdf_ recently, deleting some unused compatibility tool mappings (entries under "CompatToolMapping"), but that can not be it…
![Bildschirmfoto vom 2022-04-07 06-27-54](https://user-images.githubusercontent.com/54212019/162121336-59445def-f7ea-4eaa-a4b2-481e027ad379.png)
PS: Older versions produce the error as well, though written differently.

**Comment by nning** [comment]
`protonutils` is reading different VDF files on `list`. Would you send the following files for me to debug with, please? (You can send them to mail@nning.io.)

* `~/.local/share/Steam/config/loginusers.vdf`
* `~/.local/share/Steam/appcache/appinfo.vdf`
* `~/.local/share/Steam/config/config.vdf`
* `~/.local/share/Steam/steamapps/libraryfolders.vdf`
* `~/.local/share/Steam/userdata/1227399972/config/localconfig.vdf`
* `~/.local/share/Steam/userdata/1227399972/config/shortcuts.vdf`

One command that creates a tarball containing all those files is:

    tar cf ~/protonutils-debug.tar ~/.local/share/Steam/config/loginusers.vdf ~/.local/share/Steam/appcache/appinfo.vdf ~/.local/share/Steam/config/config.vdf ~/.local/share/Steam/steamapps/libraryfolders.vdf ~/.local/share/Steam/userdata/*/config/localconfig.vdf ~/.local/share/Steam/userdata/*/config/shortcuts.vdf

`~/protonutils-debug.tar` would contain all relevant files, then.

Thanks for reporting and helping to debug this!

**Comment by nning** [comment]
@crlmahlberg, do you have the chance to send debug info, please? If you are hesitant to share the files, I can also generate a binary with more debug output but that's probably taking more iterations.

**Comment by crlmahlberg** [comment]
Hi @nning, thanks for your answer. I'm a bit hesitant when it comes to sharing data TBH, but I would be happy with a binary that has a more verbose debug output. Thanks for your efforts!

**Comment by nning** [comment]
I prepared a branch with added debug logging (see #29).

CI generated a development binary with that feature:
https://github.com/nning/protonutils/suites/6695814930/artifacts/254295941

Run it like `DEBUG=1 ./protonutils list`, then it should output the steps it takes and the last few lines should show what your problem is connected to.
