### ISSUE TITLE
Silent hang when user is specified

### ISSUE THREAD

**Issue by L1Q** [nning/protonutils#30]
Expanding the problem mentioned in #28 into a new issue.

My ``~/.config/protonutils/protonutils.yml`` has ``user: "82996121"`` configured so ``protonutils list`` does not complain about "Several Steam users available".
As part of my troubleshooting process, I renamed ``protonutils.yml`` and ran ``protonutils list`` again.
Looks about like this (user numbers removed):
```
Warning: Several Steam users available, using [redacted]
All available users: [redacted], [redacted], [redacted]
Option "-u" can be used to specify user

vdf: unknown pack type 220
```
Using the suggested "-u" option results in the original issue: no output, complete hang with 100% single core usage.
Surprising to me, ``ge update`` was also broken like that until config rename.

**Comment by nning** [comment]
Thanks for reporting! I think I have a fix for the hanging with a given user option. Please see #28.

The error you're seeing on `protonutils list` with auto-selected user is still strange. Would you try that case with enabled debugging output and upload the files, please?

**Comment by L1Q** [comment]
> Please re-test with the following binary from CI:
https://github.com/nning/protonutils/suites/6697714136/artifacts/254433872

This issue is completely resolved in the CI build, no longer hangs with "-u" or with config!

**Comment by nning** [comment]
Perfect, thanks again for reporting!
