### ISSUE TITLE
"list" fails with "vdf: unknown pack type 220"

### ISSUE THREAD

**Issue by L1Q** [nning/protonutils#31]
> https://github.com/nning/protonutils/issues/30#issuecomment-1140294445

[debug-protonutils-list--c.txt](https://github.com/nning/protonutils/files/8791771/debug-protonutils-list--c.txt)

**Comment by nning** [comment]
The code is now ignoring more VDF parsing errors, please test the latest release:
https://github.com/nning/protonutils/releases/latest/download/protonutils

**Comment by L1Q** [comment]
It helped, thank you!

**Comment by nning** [comment]
Perfect, thanks for reporting and testing!
