### ISSUE TITLE
Cannot change to flatpak steam_root

### ISSUE THREAD

**Issue by barni2000** [nning/protonutils#33]
When i try to set steam_root the program always want to check native installation.

```
protonutils config steam_root ~/.var/app/com.valvesoftware.Steam/data/Steam/
Steam root not a directory: /home/<user>/.local/share/Steam
```

**Comment by nning** [comment]
Thanks for reporting! I fixed the issue and released [v1.6.7](https://github.com/nning/protonutils/releases/tag/v1.6.7). I already closed the issue but please let me know if it does not work for you!
