### ISSUE TITLE
Download link for latest luxtorpeda is one letter off resulting in a 404.

### ISSUE THREAD

**Issue by entrapta-dev** [nning/protonutils#34]
Trying to update luxtorpeda via `protonutils luxtorpeda update` results in a 404.  

It is trying to download:  
```
https://github.com/luxtorpeda-dev/luxtorpeda/releases/download/v64.0.0/luxtorpeda-64.0.0.tar.xz
```

The actual release download is:  
```
https://github.com/luxtorpeda-dev/luxtorpeda/releases/download/v64.0.0/luxtorpeda-v64.0.0.tar.xz
```

The issue is the `-64` versus `-v64` resulting in an error 404 file not found.

**Comment by nning** [comment]
Thanks for reporting! I fixed it and pushed [v1.6.6](https://github.com/nning/protonutils/releases/tag/v1.6.6).
