### ISSUE TITLE
[SOLVED] Manjaro linux: Steam root not a directory: /home/death/.local/share/Steam

### ISSUE THREAD

**Issue by deathxxx123** [nning/protonutils#37]
This path is wrong for Manjaro and believe for Arch too.
The path is:
~/.steam/steam/

**Comment by deathxxx123** [comment]
I see... that we have command to set a steam root folder.
So for Manjaro is:
`protonutils config steam_root ~/.steam/steam`

**Comment by nning** [comment]
Thanks for reporting!

I cannot see why the Steam client is not installing itself in `.local/share/Steam` on Manjaro. I tested it again with a fresh RPM install on Fedora and it is using that directory (but linking `.steam/steam` to it).

However, for now I think it is fine to adjust the path in the config on Manjaro.
